#
# ENV Table Settings
# All key-value pars in this section will be added as environment vars
# for any process spawned by Alacritty, including its shell.  Some 
# entries may override variables set by alacritty itself.
[env]
TERM = "alacritty"
#WINIT_X11_SCALE_FACTOR = "1.0"
#
# WINDOW settings
[window]
decorations = "none"
opacity = 0.9
padding = { x = 4, y = 10 }
#dimensions = { columns = <integer>, lines = <integer> }
#decorations = "None"
# padding = { x = 5, y = 5 }
#opacity = 1.0 <-- do not do this here (yet), your compositor should be handling this most likely.  You can tweak here later to really fine tune
#blur = true  <-- your compositor will most likely handle this too
[font]
normal = { family = "Maple Mono" }
size = 14
# builtin_box_drawing = true

[bell]
animation = "Ease"
duration = 100
color = "#222222"
#command
#
[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true #TODO: Can I have awesomeWM handle this?

[general]
live_config_reload = true

# [terminal.shell]
# program = "/sbin/nu"
# args = ["~/.config/yazelix/nushell/scripts/core/start_yazelix.nu"]
# Root level configurations
#import = [
#   "~/.config/alacritty/banginkeybinds.toml",
#   "~/.config/alacritty/dopeazztheme.toml"
#]
#
# shell = { program = '/usr/bin/fish' }
[colors]
# Abernathy theme colors (matching other terminal configs)
primary = { background = "#1f1f1f", foreground = "#d4d4d4" }

normal = { black = "#1f1f1f", red = "#d16969", green = "#608b4e", yellow = "#dcdcaa", blue = "#569cd6", magenta = "#c586c0", cyan = "#4ec9b0", white = "#d4d4d4" }

bright = { black = "#6a9955", red = "#f14c4c", green = "#23d18b", yellow = "#f5f543", blue = "#3b8eea", magenta = "#d670d6", cyan = "#29b8db", white = "#e5e5e5" }
[cursor]
style = { shape = "Block", blinking = "Off" }

[scrolling]
history = 10000

[keyboard]
bindings = [
  # Allow copy/paste
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
]
