# Root level configurations
#import = [
#   "~/.config/alacritty/banginkeybinds.toml",
#   "~/.config/alacritty/dopeazztheme.toml"
#]
#
shell = { program = '/usr/bin/fish' }
live_config_reload = true
#
# ENV Table Settings
# All key-value pars in this section will be added as environment vars
# for any process spawned by Alacritty, including its shell.  Some 
# entries may override variables set by alacritty itself.
[env]
#WINIT_X11_SCALE_FACTOR = "1.0"
#
# WINDOW settings
[window]
#dimensions = { columns = <integer>, lines = <integer> }
#decorations = "None"
padding = { x = 5, y = 5 }
#opacity = 1.0 <-- do not do this here (yet), your compositor should be handling this most likely.  You can tweak here later to really fine tune
#blur = true  <-- your compositor will most likely handle this too
[font]
normal = { family = "0xProto Nerd Font" }
size = 14
# builtin_box_drawing = true

[bell]
animation = "Ease"
duration = 100
color = "#222222"
#command
#
[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true #TODO: Can I have awesomeWM handle this?
