alias vi='nvim'
alias t='task'
alias vic='cd ~/.config && vi .'
alias vicn='cd ~/.config/nvim && vi .'
alias ls='eza --long --header --icons --git'
alias lsc='eza --all --long --header --icons --git --git-ignore'
alias cat='bat'
alias peaclock='peaclock --config-dir ~/.config/.peaclock'
