github.com:
    users:
        BigJayToDaIzo:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: BigJayToDaIzo
