theme = "everforest_dark"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = true
gutters = ["diagnostics", "line-numbers", "diff"]
rulers = [80, 120, 160]
bufferline = "multiple"
color-modes = true
idle-timeout = 1000
completion-timeout = 1000
insert-final-newline = false
trim-final-newlines = true
trim-trailing-whitespace = true
popup-border = "all"

[editor.auto-save]
focus-lost = true

[editor.file-picker]
hidden = false
max-depth = 5

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true
inlay-hints-length-limit = 3

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
  "workspace-diagnostics",
]
center = ["version-control"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "warning"


[editor.indent-guides]
render = true
skip-levels = 1

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[keys.normal.C-y]
# Open files in current window
y = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh open %{buffer_name}"
# Open the file(s) in a vertical split
v = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh vsplit %{buffer_name}"
# Open the file(s) in a horizontal split
h = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh hsplit %{buffer_name}"
