theme = "darcula"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = true
gutters = ["diagnostics", "line-numbers", "diff"]
rulers = [80, 120, 160]
bufferline = "multiple"
color-modes = true


[editor.file-picker]
hidden = false
max-depth = 5

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
  "workspace-diagnostics",
]
center = ["version-control"]

[editor.lsp]
enable = true
auto-signature-help = true
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.whitespace.characters]
# space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)
