[[language]]
name = "toml"
auto-format = true
indent = { tab-width = 2, unit = "  " }
file-types = ["toml"]
formatter = { command = "taplo", args = ["fmt", "-"] }
roots = ["toml"]

[language-server.taplo]
command = "taplo lsp"

[[language]]
name = "rust"
auto-format = true
file-types = ["rs"]

roots = ["Cargo.toml", "Cargo.lock"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

# Rust Specific
[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
